version: '3'
services:
    db:
      image: "CA4-db:latest"
      container_name: mysql-db
      volumes:
        - my-db:/var/lib/mysql/data
      ports:
        - 3300:3300
      environment:
          - MYSQL_USER: "root"
          - MYSQL_ROOT_PASSWORD: tiger123
          - MYSQL_DATABASE: users

    flask-app:
      image: CA4-Server:latest
      container_name: flask-app
      ports:
        - "5000:5000"
      environment:
          - MYSQL_HOST: "mysql-db"
          - MYSQL_PORT: 3300
          - MYSQL_USER: root
          - MYSQL_PASSWORD: tiger123
          - MYSQL_DB: users
      volumes:
        - ./app:/app
      depends_on:
        - mysql-db
        
networks:
  default:
    external:
      name: app-db-network
