version: '3'
services:
    db:
      image: "CA4-db:latest"
      container_name: mysql-db
      volumes:
        - my-db:/var/lib/mysql/data
      ports:
        - 3300:3300
      environment:
          MYSQL_ROOT_PASSWORD: tiger123
          MYSQL_DATABASE: users

    flask-app:
      image: CA4-Server:latest
      container_name: flask-app
      ports:
        - "5000:5000"
      environment:
        - DATABASE_URI=mysql://root:tiger123@db/users
      volumes:
        - ./app:/app
      depends_on:
        - db
        
networks:
  default:
    external:
      name: app-db-network
