version: '3'
services:
    db:
      image: "bionicbeavers/ca4-db:latest"
      container_name: mysql-db
      ports:
        - 3300:3300
      environment:
          MYSQL_ROOT_PASSWORD: tiger123
          MYSQL_DATABASE: users
        
    flask-app:
      image: bionicbeavers/ca4-server:latest
      container_name: flask-app
      ports:
        - "5000:5000"
      environment:
        DATABASE_URL: mysql://root:tiger123@db:3300/users
      depends_on:
        - db
        
networks:
  default:
    external:
      name: app-db-network