name: I200780 Task - Docker Compose 

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
          
      - name: Cloning bionicbeavers Repository
        run: |
          git clone https://github.com/bionicbeavers/CA4.git
          cd CA4
          
      - name: Mysql Database connectivity
        run: |
          echo "DATABASE_URL: mysql://root:tiger123@db:3300/users" > .env
          
      - name: Docker Network creation for flask and db inter-container connectivity
        run: docker network create app-db-network
        
      - name: Docker Hub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
         
      - name: Build and run Docker Containers
        run: docker-compose up --build -d
        
