name: I200780 Task - Docker Compose 

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
          
      - name: Cloning bionicbeavers Repository
        run: git clone https://github.com/bionicbeavers/CA4.git && cd CA4
          
      - name: Docker Network creation for flask and db inter-container connectivity
        run: docker network create app-db-network
        
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build docker Containers
        run: docker-compose build

      - name: run docker Containers
        run: docker-compose up -d
        
