name: I200780 Task - Docker Compose 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose
          
      - name: Clone Repository
        run: |
          git clone https://github.com/bionicbeavers/CA4.git
          cd CA4
          
      - name: Set up Environment Variables
        run: |
          echo "DATABASE_URI=mysql://root:tiger123@db/users" > .env
          
      - name: Create Docker Network
        run: docker network create app-db-network
        
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
         
      - name: Build and Start Docker Containers
        run: docker-compose up --build -d
        
 
